### ISSUE TITLE
How to get dataset_train.txt？

### ISSUE THREAD

**Issue by suntianren** [JusperLee/Looking-to-Listen-at-the-Cocktail-Party#12]
No such file or directory: './AV_model_database/dataset_train.txt'.

**Comment by JusperLee** [comment]
You need to use scripts to generate.

**Comment by suntianren** [comment]
I don't really understan how to generate dataset_train.txt using data in avspeech_train. What format should data in "dataset_train.txt" be? Could you please describe it in more details？

**Comment by JusperLee** [comment]
https://github.com/JusperLee/Looking-to-Listen-at-the-Cocktail-Party/blob/master/data/AV_data_log.py
