### ISSUE TITLE
你好，在知乎回答中注意到你在视频帧扩展数据维度与音频保持一致时提到使用最近邻内插法，但是在代码中好像你使用的还是双线性内插法

### ISSUE THREAD

**Issue by Jasonheartesyu** [JusperLee/Looking-to-Listen-at-the-Cocktail-Party#3]
还有想请教一下，我是一个小白，正在对音视频语音分离进行研究，之前一直在跑bill写的代码，但是model_v2的效果一直不好，我所做的改变只是将bill中的双线性内插改成了最近邻插值法，效果会提升零点几dB，也尝试过增大混合训练数据集，使用过7万，21万的混合语音数据集进行训练，损耗值输出都在0.6几，而且有很多epoch都没有损耗下降，差不多50epoch只有6、7个epoch下降，使用测试集对训练好的模型进行测试一直在3dB左右，如果使用训练集测试也只是到达6dB左右，你在尝试bill的代码有存在这些问题吗？我原来有打算把脸部的特征提取变为唇部的特征提取，但是文章曾明确说过这样做效果几乎没有差异，而且文章提到了除嘴部以外的其他区域也会对语音分离的效果有作用，所以就没有进行此类尝试，想再请教一下，你觉得脸部替换为唇部特征有必要吗？

**Comment by JusperLee** [comment]
你好，对于这个Google的方法。我做了一定的尝试，我使用了10万的数据来训练该模型，并不能对模型有着很大的提升。我认为，Google能够实现10.0db的结果是由于他大规模数据集所导致的，因为我怀疑他的测试数据可能存在训练集中产生过拟合的现象。在我自己实验的结果中最终得到的结果也并不能得到论文中的效果，我在此之后就没有深入研究该方法。我在尝试bill的代码时发现，其loss下降非常慢，这可能与其视觉和听觉特征的提取和loss的设定有关。就我目前所看的Audio Visual在不同领域的研究中，大部分人使用的都是嘴唇部分的图像，而且我认为视觉的输入对于语音分离的效果影响不是很大（可以参考一些比较perfect的纯语音分离的work，你可以看一下Dual-Path-RNN）。所以，我觉得是否将脸部替换为唇部特征是没有什么必要性的，应该是无法提升该模型的。我最近在做Audio Visual的语音分离可以在非大量数据集上得到较好的结果，由于最近在整理和投稿论文目前还不能公开。

**Comment by Jasonheartesyu** [comment]
嗯嗯，谢谢你的回答，十分感谢你的建议！！！预祝paper投稿成功！

**Comment by JusperLee** [comment]
没关系，我将该issue关闭了
