### ISSUE TITLE
Result of test.py file

### ISSUE THREAD

**Issue by 83344rushikesh** [JusperLee/Looking-to-Listen-at-the-Cocktail-Party#6]
@JusperLee after running the test.py file the pred folder is created where the .wav files are generating but there is no voice in all the .wav files all the files are silent. Why is that so?

**Comment by JusperLee** [comment]
You need to see for yourself if there is a problem with the preprocessed files generated.

**Comment by 83344rushikesh** [comment]
@JusperLee your GPU size was in TB or GB ?

**Comment by JusperLee** [comment]
GB

**Comment by JusperLee** [comment]
one gpu was in 64GB

**Comment by 83344rushikesh** [comment]
@JusperLee okay..All the preprocessing has been done according to your readme only. Can you give possible solutions to this ?

**Comment by JusperLee** [comment]
Due to the different experimental environments, I think you need to carefully check your code, including testing and preprocessing. This code did not show the above problems during my experiment.

**Comment by 83344rushikesh** [comment]
@JusperLee what was the accuracy of your audio visual model ?

**Comment by JusperLee** [comment]
Since I can't get the complete data set, the results I get are not as good
as the values in the paper.

83344rushikesh <notifications@github.com> 于2020年3月30日周一 上午12:00写道：

**Comment by 83344rushikesh** [comment]
@JusperLee Do you have your personal paper available for this in english ?

**Comment by JusperLee** [comment]
Looking to Listen at the Cocktail Party: A Speaker-Independent Audio-Visual Model for Speech Separation

**Comment by 83344rushikesh** [comment]
@JusperLee How to use this model on a new video? Can you share that code?

**Comment by JusperLee** [comment]
AV_Model_Deep.log

**Comment by JusperLee** [comment]
You just need to change the input video.

**Comment by 83344rushikesh** [comment]
@JusperLee For that new video we again need to do the face embedding like all the preprocessing from start right ?

**Comment by JusperLee** [comment]
Yes

**Comment by 83344rushikesh** [comment]
@JusperLee For how many speakers it will work?

**Comment by 83344rushikesh** [comment]
@JusperLee  I'm getting following error while running the test.py file
Traceback (most recent call last):
  File "test.py", line 92, in <module>
    T = utils.fast_istft(F,power=False)
  File "/home/lenovo/Downloads/Looking-to-Listen-at-the-Cocktail-Party-master/utils.py", line 75, in fast_istft
    data = istft(real_imag_shrink(data))
  File "/home/lenovo/Downloads/Looking-to-Listen-at-the-Cocktail-Party-master/utils.py", line 30, in istft
    Total[start:end] = Total[start:end] + data[i, :] * windows
ValueError: operands could not be broadcast together with shapes (257,) (512,)

**Comment by JusperLee** [comment]
1. This model does not limit the number of people mixed.
2. The different dimensions may be a problem with your own operation, which I cannot help.

**Comment by 83344rushikesh** [comment]
@JusperLee there should be a one dimension?

**Comment by 83344rushikesh** [comment]
@JusperLee At the place of 257 there should be 512 right?

**Comment by JusperLee** [comment]
I think you can check this out. These questions are very basic.
