### ISSUE TITLE
operands error

### ISSUE THREAD

**Issue by 83344rushikesh** [JusperLee/Looking-to-Listen-at-the-Cocktail-Party#7]
@JusperLee Please tell the solution for that last issue as I'm very new to this?

**Comment by JusperLee** [comment]
I think you can try to solve this problem yourself, because the length of the data we use will be inconsistent.  The above error is prompted because the array size is inconsistent.  Since this is not a problem with the code, I hope you can patiently check the problem and solve it. Thank you

**Comment by 83344rushikesh** [comment]
@JusperLee So is this is the problem because of the input size?
